# Generated by Django 5.0.2 on 2024-03-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_message_is_user_leaderboard_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-score', 'timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
