# Generated by Django 5.0.2 on 2024-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_leaderboard_options_message_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='OpenAI_thread_id',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='num_str',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_language',
            field=models.CharField(default='EN', max_length=5),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
