# Generated by Django 5.0.3 on 2024-03-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_chatsession_openai_thread_id_leaderboard_num_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='is_successful',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
